IF DB_ID('AirlineAnalysis') IS NULL
BEGIN
	CREATE DATABASE [AirlineAnalysis];
END
GO

USE [AirlineAnalysis];
GO

DROP TABLE IF EXISTS dbo.flights;
DROP TABLE IF EXISTS dbo.airports;
DROP TABLE IF EXISTS dbo.airlines;
DROP TABLE IF EXISTS dbo.cancellation_codes;
GO


CREATE TABLE airlines (
	AIRLINE_CODE VARCHAR(5) PRIMARY KEY,
	AIRLINE_NAME VARCHAR(50)
);


CREATE TABLE airports(
	AIRPORT_CODE VARCHAR(5) PRIMARY KEY,
	AIRPORT_NAME VARCHAR(100),
	CITY VARCHAR(50),
	STATE VARCHAR(10),
	COUNTRY VARCHAR(50),
	LATITUDE DECIMAL(10,7),
	LONGITUDE DECIMAL (10,7)
);

CREATE TABLE cancellation_codes(
	CANCELLATION_REASON VARCHAR(1) PRIMARY KEY,
	CANCELLATION_DESCRIPTION VARCHAR(30)
);

CREATE TABLE flights (
	YEAR SMALLINT,
	MONTH SMALLINT,
	DAY SMALLINT,
	DAY_OF_WEEK SMALLINT,
	AIRLINE_CODE VARCHAR(5),
	FLIGHT_NUMBER INT,
	TAIL_NUMBER VARCHAR(10),
	ORIGIN_AIRPORT VARCHAR(5),
	DESTINATION_AIRPORT VARCHAR(5),
	SCHEDULED_DEPARTURE INT,
	DEPARTURE_TIME INT,
	DEPARTURE_DELAY SMALLINT,
	TAXI_OFF SMALLINT,
	WHEELS_OFF SMALLINT,
	SCHEDULED_TIME SMALLINT,
	ELAPSED_TIME SMALLINT,
	AIR_TIME SMALLINT,
	DISTANCE SMALLINT,
	WHEELS_ON SMALLINT,
	TAXI_IN SMALLINT,
	SCHEDULED_ARRIVAL SMALLINT,
	ARRIVAL_TIME SMALLINT,
	ARRIVAL_DELAY SMALLINT,
	DIVERTED SMALLINT,
	CANCELLED SMALLINT,
	CANCELLATION_REASON VARCHAR(1),
	AIR_SYSTEM_DELAY SMALLINT,
	SECURITY_DELAY SMALLINT, 
	AIRLINE_DELAY SMALLINT,
	LATE_AIRCRAFT_DELAY SMALLINT,
	WEATHER_DELAY SMALLINT,
	FOREIGN KEY(AIRLINE_CODE) REFERENCES dbo.airlines(AIRLINE_CODE),
	FOREIGN KEY(ORIGIN_AIRPORT) REFERENCES dbo.airports(AIRPORT_CODE),
	FOREIGN KEY(DESTINATION_AIRPORT) REFERENCES dbo.airports(AIRPORT_CODE),
	FOREIGN KEY(CANCELLATION_REASON) REFERENCES dbo.cancellation_codes(CANCELLATION_REASON)
	);


BULK INSERT dbo.flights
FROM 'C:\Users\judeb\OneDrive\Documents\AirlineAnalysisProject\airline_data\flights.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a'
);

BULK INSERT dbo.airports
FROM 'C:\Users\judeb\OneDrive\Documents\AirlineAnalysisProject\airline_data\airports.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a'
);

BULK INSERT dbo.airlines
FROM 'C:\Users\judeb\OneDrive\Documents\AirlineAnalysisProject\airline_data\airlines.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a'
);

BULK INSERT dbo.cancellation_codes
FROM 'C:\Users\judeb\OneDrive\Documents\AirlineAnalysisProject\airline_data\cancellation_codes.csv'
WITH (
    FIRSTROW = 2,
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a'
);

SELECT * FROM dbo.airlines;
SELECT * FROM dbo.airports;
SELECT * FROM dbo.cancellation_codes;
SELECT * FROM dbo.flights;